// @ts-check

/**
 * @fileoverview List of blocks to be supported in the compiler compatibility layer.
 * This is only for native blocks. Extensions should not be listed here.
 */

// Please keep these lists alphabetical.

const stacked = [
    'looks_changestretchby',
    'looks_clearmodelcolor',
    'looks_hideallsprites',
    'looks_sayforsecs',
    'looks_setmodelcolor',
    'looks_setstretchto',
    'looks_switchbackdroptoandwait',
    'looks_thinkforsecs',
    'media_duration',
    'media_loaded',
    'media_pause',
    'media_play',
    'media_restart',
    'media_setimageurl',
    'media_setsize',
    'media_setuploaded',
    'media_setvideourl',
    'media_time',
    'mouse_hidecursor',
    'mouse_lock',
    'mouse_setmode',
    'mouse_setsensitivity',
    'mouse_setthirdpersondistance',
    'mouse_showcursor',
    'mouse_unlock',
    'motion_align_scene',
    'motion_changezby',
    'motion_glidesecstoxy',
    'motion_glideto',
    'motion_goto',
    'motion_pointtowards',
    'motion_scroll_right',
    'motion_scroll_up',
    'motion_setz',
    'motion_turnpitchby',
    'motion_turnrollby',
    'motion_turnyawby',
    'network_confirmsafety',
    'network_isconfirmed',
    'network_jsonget',
    'network_jsonset',
    'network_jsonstringify',
    'network_jsonvalid',
    'network_responseok',
    'network_responsestatus',
    'network_responsetext',
    'network_sendapirequest',
    'network_sendrequest',
    'scene3d_addbackdrop',
    'scene3d_followthisactor',
    'scene3d_nextbackdrop',
    'scene3d_pointcameraat',
    'scene3d_setambientlight',
    'scene3d_setcamerafov',
    'scene3d_setcameraposition',
    'scene3d_setcamerasmoothingduration',
    'scene3d_setenvironmentpreset',
    'scene3d_setfollowdistance',
    'scene3d_setfollowheight',
    'scene3d_setfogamount',
    'scene3d_setgroundcolor',
    'scene3d_setkeylight',
    'scene3d_setkeylightposition',
    'scene3d_setskycolor',
    'scene3d_setsunangle',
    'scene3d_setsuncolor',
    'scene3d_stopfollowing',
    'scene3d_switchbackdrop',
    'scene3d_turncameraleftrightby',
    'scene3d_turncameraupdownby',
    'sensing_askandwait',
    'sensing_setdragmode',
    'sound_changeeffectby',
    'sound_changevolumeby',
    'sound_changestereopanby',
    'sound_cleareffects',
    'sound_play',
    'sound_playuntildone',
    'sound_seteffectto',
    'sound_setstereopan',
    'sound_setvolumeto',
    'sound_stopallsounds'
];

const inputs = [
    'media_duration',
    'media_loaded',
    'media_time',
    'mouse_buttondown',
    'mouse_deltax',
    'mouse_deltay',
    'mouse_mode',
    'motion_xscroll',
    'motion_yscroll',
    'motion_zposition',
    'network_isconfirmed',
    'network_jsonget',
    'network_jsonset',
    'network_jsonstringify',
    'network_jsonvalid',
    'network_responseok',
    'network_responsestatus',
    'network_responsetext',
    'sound_stereopan',
    'sensing_loud',
    'sensing_loudness',
    'sensing_online',
    'sensing_userid',
    'sound_volume'
];

module.exports = {
    stacked,
    inputs
};
